spring:
  profiles:
    active:
    - dev
---
server:
  port: 6003
  
spring:
  profiles: dev  #开发环境
  
eureka:
  instance:
    #eureka服务端的实例名称
    #hostname: localhost
    hostname: eureka6003.com
  client:
    #false表示不向注册中心注册自己。
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka6002.com:6002/eureka/,http://eureka6001.com:6001/eureka/
---
server:
  port: 5003
  
spring:
  profiles: test  #测试环境
  
eureka:
  instance:
    #eureka服务端的实例名称
    #hostname: localhost
    hostname: eureka5003.com
  client:
    #false表示不向注册中心注册自己。
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka5002.com:5002/eureka/,http://eureka5001.com:5001/eureka/
