spring:
  profiles:
    active:
    - dev
---
server:
  port: 9002
spring:
    profiles: dev  #开发环境
    application:
        name: MICROSERVICECLOUD-SD
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://LOCALHOST:3306/https_url?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        # 初始化大小，最小，最大
        initialSize: 64
        minIdle: 64
        maxActive: 1024
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
        filters: stat,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        # useGlobalDataSourceStat: true
    http:
      multipart:   # 文件上传
        max-file-size: 100MB
        max-request-size: 100MB
mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:6001/eureka
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/,http://eureka6003.com:6003/eureka/
  instance:
    instance-id: MICROSERVICECLOUD-SD-9002
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: microservicecloud-pms
  company.name: www.wk.com
---
server:
  port: 9002
spring:
    profiles: test  #测试环境
    application:
        name: MICROSERVICECLOUD-SD
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://LOCALHOST:3306/https_url?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        # 初始化大小，最小，最大
        initialSize: 64
        minIdle: 64
        maxActive: 1024
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
        filters: stat,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        # useGlobalDataSourceStat: true
    http:
      multipart:   # 文件上传
        max-file-size: 100MB
        max-request-size: 100MB
mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:5001/eureka
      defaultZone: http://eureka5001.com:5001/eureka/,http://eureka5002.com:5002/eureka/,http://eureka5003.com:5003/eureka/
  instance:
    instance-id: MICROSERVICECLOUD-SD-9002
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: microservicecloud-pms
  company.name: www.wk.com
